export const users: any = {
  module: () => import('./users.module').then((m) => m.UsersPageModule),
  routes: [
    {
      path: 'users/search',
      name: 'users.search.title',
      icon: 'people',
      menu: 'primary',
      view: 'search',
      auth: ['administrator', 'supervisor']
    },
    {
      path: 'users/select/:_id',
      name: 'users.select.title',
      icon: 'search',
      menu: '',
      view: 'select',
      auth: ['administrator', 'supervisor']
    },
    {
      path: 'users/create',
      name: 'users.create.title',
      icon: 'create',
      menu: '',
      view: 'create',
      auth: ['administrator', 'supervisor']
    },
    {
      path: 'users/update/:_id',
      name: 'users.update.title',
      icon: 'create',
      menu: '',
      view: 'update',
      auth: ['administrator', 'supervisor']
    },
    {
      path: 'users/delete/:_id',
      name: 'users.delete.title',
      icon: 'create',
      menu: '',
      view: 'delete',
      auth: ['administrator']
    },
    {
      path: 'users/export',
      name: 'users.export.title',
      icon: 'cloud-download',
      menu: '',
      view: 'export',
      auth: ['administrator']
    },
    {
      path: 'users/import',
      name: 'users.import.title',
      icon: 'cloud-upload',
      menu: '',
      view: 'import',
      auth: ['administrator']
    }
  ],
  config: {
    name: 'users',
    i18n: {
      es: {
        'search.title': 'Usuarios',
        'select.title': 'Usuario',
        'create.title': 'Crear usuario',
        'update.title': 'Editar usuario',
        'delete.title': 'Borrar usuario',
        'export.title': 'Exportar usuarios',
        'import.title': 'Importar usuarios',

        'search.legend': 'Busca en usuarios',
        'delete.legend': '¿Realmente quieres borrar el usuario <strong>{{name}}</strong>? Esta acción no se puede revertir.',

        '_id.label': 'Usuario',
        '_id.required': 'El usuario es requerido',
        '_id.invalid': 'El usuario es inválido',
        '_id.valid': 'Define el usuario',

        'name.label': 'Nombre',
        'name.required': 'El nombre es requerido',
        'name.invalid': 'El nombre es inválido',
        'name.valid': 'Define el nombre',

        'group.label': 'Grupo',
        'group.required': 'El grupo es requerido',
        'group.invalid': 'El grupo es inválido',
        'group.valid': 'Define el grupo',

        'image.label': 'Imagen',
        'image.required': 'La imagen es requerida',
        'image.invalid': 'La imagen es inválida',
        'image.valid': 'Define la imagen',

        'notes.label': 'Notas',
        'notes.required': 'Las notas son requeridas',
        'notes.invalid': 'Las notas son inválidas',
        'notes.valid': 'Define las notas',

        'phone.label': 'Teléfono',
        'phone.required': 'El teléfono es requerido',
        'phone.invalid': 'El teléfono es inválido',
        'phone.valid': 'Define el teléfono',

        'email.label': 'E-mail',
        'email.required': 'El e-mail es requerido',
        'email.invalid': 'El e-mail es inválido',
        'email.valid': 'Define el e-mail',

        'address.label': 'Dirección',
        'address.required': 'La dirección es requerida',
        'address.invalid': 'La dirección es inválida',
        'address.valid': 'Define la dirección',

        'address.street': 'Calle y altura',
        'address.city': 'Ciudad',
        'address.state': 'Provincia',
        'address.country': 'País',
        'address.zipcode': 'CP',
        'address.position.0': 'Latitud',
        'address.position.1': 'Longitud',

        'website.label': 'Sitio Web',
        'website.required': 'El sitio web es requerido',
        'website.invalid': 'El sitio web es inválido',
        'website.valid': 'Define el sitio web',

        'person.header': 'Identidad',
        'person.legend': 'Define las opciones de facturación para este usuario.',
        'person.uid': 'Person UID',
        'person.uid[ar]': 'CUIT',
        'person.uid[bo]': 'NIT',
        'person.uid[br]': 'CPF',
        'person.uid[cl]': 'RUT',
        'person.uid[py]': 'RUC',
        'person.uid[uy]': 'RUT',
        'person.uid.required': 'El valor es requerido',
        'person.uid.invalid': 'El valor es inválido',
        'person.uid.valid': 'Define el valor',
        'person.name': 'Denominación',
        'person.name.required': 'La denominación es requerida',
        'person.name.invalid': 'La denominación es inválida',
        'person.name.valid': 'Define la denominación',
        'person.group': 'Grupo',
        'person.group.required': 'El grupo es requerido',
        'person.group.invalid': 'El grupo es inválido',
        'person.group.valid': 'Define el grupo',
        'person.start': 'Fecha de inicio',
        'person.start.required': 'La fecha es requerida',
        'person.start.invalid': 'La fecha es inválida',
        'person.start.valid': 'Define la fecha',
        'person.state_uid': 'State UID',
        'person.state_uid[ar]': 'IIBB',
        'person.state_uid[bo]': 'En estado',
        'person.state_uid[br]': 'En estado',
        'person.state_uid[cl]': 'En estado',
        'person.state_uid[py]': 'En estado',
        'person.state_uid[uy]': 'En estado',
        'person.state_uid.required': 'El valor es requerido',
        'person.state_uid.invalid': 'El valor es inválido',
        'person.state_uid.valid': 'Define el valor',
        'person.local_uid': 'Local UID',
        'person.local_uid[ar]': 'En ciudad',
        'person.local_uid[bo]': 'En ciudad',
        'person.local_uid[br]': 'En ciudad',
        'person.local_uid[cl]': 'En ciudad',
        'person.local_uid[py]': 'En ciudad',
        'person.local_uid[uy]': 'En ciudad',
        'person.local_uid.required': 'El valor es requerido',
        'person.local_uid.invalid': 'El valor es inválido',
        'person.local_uid.valid': 'Define el valor',

        'locale.header': 'Región e idioma',
        'locale.legend': 'Define las opciones de localización de este usuario.',
        'locale.language': 'Idioma',
        'locale.language.required': 'El idioma es requerido',
        'locale.language.invalid': 'El idioma es inválido',
        'locale.language.valid': 'Define el idioma',
        'locale.language.value[es]': 'Español',
        'locale.language.value[en]': 'Inglés',
        'locale.language.value[pt]': 'Portugués',
        'locale.country': 'País',
        'locale.country.required': 'El país es requerido',
        'locale.country.invalid': 'El país es inválido',
        'locale.country.valid': 'Define el país',
        'locale.country.value[ar]': 'Argentina',
        'locale.country.value[br]': 'Brasil',
        'locale.country.value[cl]': 'Chile',
        'locale.country.value[py]': 'Paraguay',
        'locale.country.value[uy]': 'Uruguay',
        'locale.currency': 'Moneda',
        'locale.currency.required': 'La moneda es requerida',
        'locale.currency.invalid': 'La moneda es inválida',
        'locale.currency.valid': 'Define la moneda',
        'locale.currency.value[ars]': 'Peso argentino',
        'locale.currency.value[brl]': 'Real brasileño',
        'locale.currency.value[clp]': 'Peso chileno',
        'locale.currency.value[pyg]': 'Guaraní paraguayo',
        'locale.currency.value[uyu]': 'Peso uruguayo',

        'security.header': 'Seguridad',
        'security.legend': 'Define las opciones de seguridad de este usuario.',

        'recovery.label': 'PIN',
        'recovery.required': 'El PIN es requerido',
        'recovery.invalid': 'El PIN debe tener al menos 5 caracteres',
        'recovery.valid': 'Define el PIN',

        'password.label': 'Clave',
        'password.required': 'La clave es requerida',
        'password.invalid': 'La clave debe tener al menos 5 caracteres',
        'password.valid': 'Define la clave',

        'security.label': 'Ingreso',
        'security.required': 'El ingreso es requerido',
        'security.invalid': 'El ingreso es inválido',
        'security.valid': 'Define el ingreso',
        'security.value[standard]': 'Estándar',
        'security.value[2fa]': 'Segundo factor',

        'access.label': 'Acceso',
        'access.required': 'El acceso es requerido',
        'access.invalid': 'El acceso es inválido',
        'access.valid': 'Define el acceso',
        'access.value[administrator]': 'Administrador',
        'access.value[supervisor]': 'Supervisor',
        'access.value[operator]': 'Operador',
        'access.value[user]': 'Usuario',

        'status.label': 'Estado',
        'status.required': 'El estado es requerido',
        'status.invalid': 'El estado es inválido',
        'status.valid': 'Define el estado',
        'status.value[enabled]': 'Activo',
        'status.value[disabled]': 'Inactivo',

        'places.header': 'Puntos de venta',
        'places.legend': 'Define las opciones de este usuario en los puntos de venta de esta cuenta.',
        'places.place': 'Punto de venta',
        'places.place.required': 'El punto de venta es requerido',
        'places.place.invalid': 'El punto de venta es inválido',
        'places.place.valid': 'Define el punto de venta',

        'created_at.label': 'Creación',
        'created_at.required': 'La fecha de creación es requerida',
        'created_at.invalid': 'La fecha de creación es inválida',
        'created_at.valid': 'Define la fecha de creación',

        'updated_at.label': 'Actualización',
        'updated_at.required': 'La fecha de actualización es requerida',
        'updated_at.invalid': 'La fecha de actualización es inválida',
        'updated_at.valid': 'Define la fecha de actualización'
      }
    }
  }
};
