version: "3"
services:

  bot:
    container_name: bot
    restart: always
    build: ./bot
    image: bot
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379

networks:
  default:
    external:
      name: bot
