export const places: any = {
  module: () => import('./places.module').then((m) => m.PlacesPageModule),
  routes: [
    {
      path: 'places/search',
      name: 'places.search.title',
      icon: 'storefront',
      menu: 'primary',
      view: 'search',
      auth: ['administrator', 'supervisor']
    },
    {
      path: 'places/select/:_id',
      name: 'places.select.title',
      icon: 'search',
      menu: '',
      view: 'select',
      auth: ['administrator', 'supervisor']
    },
    {
      path: 'places/create',
      name: 'places.create.title',
      icon: 'create',
      menu: '',
      view: 'create',
      auth: ['administrator']
    },
    {
      path: 'places/update/:_id',
      name: 'places.update.title',
      icon: 'create',
      menu: '',
      view: 'update',
      auth: ['administrator']
    },
    {
      path: 'places/delete/:_id',
      name: 'places.delete.title',
      icon: 'create',
      menu: '',
      view: 'delete',
      auth: ['administrator']
    },
    {
      path: 'places/export',
      name: 'places.export.title',
      icon: 'cloud-download',
      menu: '',
      view: 'export',
      auth: ['administrator']
    },
    {
      path: 'places/import',
      name: 'places.import.title',
      icon: 'cloud-upload',
      menu: '',
      view: 'import',
      auth: ['administrator']
    }
  ],
  config: {
    name: 'places',
    i18n: {
      es: {
        'search.title': 'Puntos de venta',
        'select.title': 'Punto de venta',
        'create.title': 'Crear punto de venta',
        'update.title': 'Editar punto de venta',
        'delete.title': 'Borrar punto de venta',
        'export.title': 'Exportar puntos de venta',
        'import.title': 'Importar puntos de venta',

        'search.legend': 'Busca en puntos de venta',
        'delete.legend': '¿Realmente quieres borrar el punto de venta <strong>{{name}}</strong>? Esta acción no se puede revertir.',

        '_id.label': 'Punto de venta',
        '_id.required': 'El punto de venta es requerido',
        '_id.invalid': 'El punto de venta es inválido',
        '_id.valid': 'Define el punto de venta',

        'name.label': 'Nombre',
        'name.required': 'El nombre es requerido',
        'name.invalid': 'El nombre es inválido',
        'name.valid': 'Define el nombre',

        'group.label': 'Grupo',
        'group.required': 'El grupo es requerido',
        'group.invalid': 'El grupo es inválido',
        'group.valid': 'Define el grupo',

        'image.label': 'Imagen',
        'image.required': 'La imagen es requerida',
        'image.invalid': 'La imagen es inválida',
        'image.valid': 'Define la imagen',

        'notes.label': 'Notas',
        'notes.required': 'Las notas son requeridas',
        'notes.invalid': 'Las notas son inválidas',
        'notes.valid': 'Define las notas',

        'phone.label': 'Teléfono',
        'phone.required': 'El teléfono es requerido',
        'phone.invalid': 'El teléfono es inválido',
        'phone.valid': 'Define el teléfono',

        'email.label': 'E-mail',
        'email.required': 'El e-mail es requerido',
        'email.invalid': 'El e-mail es inválido',
        'email.valid': 'Define el e-mail',

        'address.label': 'Dirección',
        'address.required': 'La dirección es requerida',
        'address.invalid': 'La dirección es inválida',
        'address.valid': 'Define la dirección',

        'address.street': 'Calle y altura',
        'address.city': 'Ciudad',
        'address.state': 'Provincia',
        'address.country': 'País',
        'address.zipcode': 'CP',
        'address.position.0': 'Latitud',
        'address.position.1': 'Longitud',

        'website.label': 'Sitio Web',
        'website.required': 'El sitio web es requerido',
        'website.invalid': 'El sitio web es inválido',
        'website.valid': 'Define el sitio web',

        'person.header': 'Identidad',
        'person.legend': 'Define las opciones de facturación para este punto de venta.',
        'person.uid': 'Person UID',
        'person.uid[ar]': 'CUIT',
        'person.uid[bo]': 'NIT',
        'person.uid[br]': 'CPF',
        'person.uid[cl]': 'RUT',
        'person.uid[py]': 'RUC',
        'person.uid[uy]': 'RUT',
        'person.uid.required': 'El valor es requerido',
        'person.uid.invalid': 'El valor es inválido',
        'person.uid.valid': 'Define el valor',
        'person.name': 'Denominación',
        'person.name.required': 'La denominación es requerida',
        'person.name.invalid': 'La denominación es inválida',
        'person.name.valid': 'Define la denominación',
        'person.group': 'Grupo',
        'person.group.required': 'El grupo es requerido',
        'person.group.invalid': 'El grupo es inválido',
        'person.group.valid': 'Define el grupo',
        'person.start': 'Fecha de inicio',
        'person.start.required': 'La fecha es requerida',
        'person.start.invalid': 'La fecha es inválida',
        'person.start.valid': 'Define la fecha',
        'person.state_uid': 'State UID',
        'person.state_uid[ar]': 'IIBB',
        'person.state_uid[bo]': 'En estado',
        'person.state_uid[br]': 'En estado',
        'person.state_uid[cl]': 'En estado',
        'person.state_uid[py]': 'En estado',
        'person.state_uid[uy]': 'En estado',
        'person.state_uid.required': 'El valor es requerido',
        'person.state_uid.invalid': 'El valor es inválido',
        'person.state_uid.valid': 'Define el valor',
        'person.local_uid': 'Local UID',
        'person.local_uid[ar]': 'En ciudad',
        'person.local_uid[bo]': 'En ciudad',
        'person.local_uid[br]': 'En ciudad',
        'person.local_uid[cl]': 'En ciudad',
        'person.local_uid[py]': 'En ciudad',
        'person.local_uid[uy]': 'En ciudad',
        'person.local_uid.required': 'El valor es requerido',
        'person.local_uid.invalid': 'El valor es inválido',
        'person.local_uid.valid': 'Define el valor',

        'locale.header': 'Región e idioma',
        'locale.legend': 'Define las opciones de localización para este punto de venta.',
        'locale.language': 'Idioma',
        'locale.language.required': 'El idioma es requerido',
        'locale.language.invalid': 'El idioma es inválido',
        'locale.language.valid': 'Define el idioma',
        'locale.language.value[es]': 'Español',
        'locale.language.value[en]': 'Inglés',
        'locale.language.value[pt]': 'Portugués',
        'locale.country': 'País',
        'locale.country.required': 'El país es requerido',
        'locale.country.invalid': 'El país es inválido',
        'locale.country.valid': 'Define el país',
        'locale.country.value[ar]': 'Argentina',
        'locale.country.value[br]': 'Brasil',
        'locale.country.value[cl]': 'Chile',
        'locale.country.value[py]': 'Paraguay',
        'locale.country.value[uy]': 'Uruguay',
        'locale.currency': 'Moneda',
        'locale.currency.required': 'La moneda es requerida',
        'locale.currency.invalid': 'La moneda es inválida',
        'locale.currency.valid': 'Define la moneda',
        'locale.currency.value[ars]': 'Peso argentino',
        'locale.currency.value[brl]': 'Real brasileño',
        'locale.currency.value[clp]': 'Peso chileno',
        'locale.currency.value[pyg]': 'Guaraní paraguayo',
        'locale.currency.value[uyu]': 'Peso uruguayo',

        'device.header': 'Impresora',
        'device.legend': 'Define las opciones de impresión para este punto de venta.',
        'device.uid': 'Número',
        'device.uid.required': 'El número es requerido',
        'device.uid.invalid': 'El número es inválido',
        'device.uid.valid': 'Define el número',
        'device.name': 'Denominación',
        'device.name.required': 'La denominación es requerida',
        'device.name.invalid': 'La denominación es inválida',
        'device.name.valid': 'Define la denominación',
        'device.group': 'Grupo',
        'device.group.required': 'El grupo es requerido',
        'device.group.invalid': 'El grupo es inválido',
        'device.group.valid': 'Define el grupo',
        'device.paper': 'Papel',
        'device.paper.required': 'El papel es requerido',
        'device.paper.invalid': 'El papel es inválido',
        'device.paper.valid': 'Define el papel',

        'config.header': 'Personalización',
        'config.legend': 'Define las opciones de personalización para este punto de venta.',
        'config.theme': 'Tema',
        'config.theme.required': 'El tema es requerido',
        'config.theme.invalid': 'El tema es inválido',
        'config.theme.valid': 'Define el tema',
        'config.theme.value[light]': 'Claro',
        'config.theme.value[dark]': 'Oscuro',
        'config.color': 'Color de fondo',
        'config.color.required': 'El color es requerido',
        'config.color.invalid': 'El color es inválido',
        'config.color.valid': 'Define el color',
        'config.color_contrast': 'Color de texto',
        'config.color_contrast.required': 'El color es requerido',
        'config.color_contrast.invalid': 'El color es inválido',
        'config.color_contrast.valid': 'Define el color',
        'config.image': 'Imagen de fondo',
        'config.image.required': 'La imagen es requerida',
        'config.image.invalid': 'La imagen es inválida',
        'config.image.valid': 'Define la imagen',
        'config.panel': 'Panel',
        'config.panel.required': 'El panel es requerido',
        'config.panel.invalid': 'El panel es inválido',
        'config.panel.valid': 'Define el panel',

        'account.label': 'Cuenta',
        'account.required': 'La cuenta es requerida',
        'account.invalid': 'La cuenta es inválida',
        'account.valid': 'Define la cuenta',

        'created_at.label': 'Creación',
        'created_at.required': 'La fecha de creación es requerida',
        'created_at.invalid': 'La fecha de creación es inválida',
        'created_at.valid': 'Define la fecha de creación',

        'updated_at.label': 'Actualización',
        'updated_at.required': 'La fecha de actualización es requerida',
        'updated_at.invalid': 'La fecha de actualización es inválida',
        'updated_at.valid': 'Define la fecha de actualización'
      }
    }
  }
};
