version: "3"
services:

  app:
    container_name: app
    restart: always
    build: ./app
    image: app
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017

networks:
  default:
    external:
      name: app
